# Generated by Django 3.2.6 on 2021-12-01 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('firstEntered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('serial',),
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('dvm', 'DVM'), ('osc', 'OSCILLASCOPE'), ('actrl', 'ANALOG'), ('rctrl', 'RELAY'), ('eload', 'E-LOAD')], max_length=25)),
                ('serialNumber', models.CharField(max_length=25)),
                ('kepcoNumber', models.CharField(max_length=25)),
                ('calibrationDate', models.DateField()),
                ('expirationDate', models.DateField()),
                ('resourceID', models.CharField(blank=True, max_length=25, null=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('firstEntered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('firstEntered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='scripts')),
                ('dvm', models.PositiveIntegerField(choices=[(0, 'n/a'), (1, 'one'), (2, 'two')])),
                ('osc', models.PositiveIntegerField(choices=[(0, 'n/a'), (1, 'one'), (2, 'two')])),
                ('rctrl', models.PositiveIntegerField(choices=[(0, 'n/a'), (1, 'one'), (2, 'two')])),
                ('actrl', models.PositiveIntegerField(choices=[(0, 'n/a'), (1, 'one'), (2, 'two')])),
                ('eload', models.PositiveIntegerField(choices=[(0, 'n/a'), (1, 'one'), (2, 'two')])),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('firstEntered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('firstEntered', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('instruments', models.ManyToManyField(blank=True, to='ad.Instrument')),
                ('products', models.ManyToManyField(blank=True, to='ad.Product')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('firstEntered', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ad.product')),
                ('scripts', models.ManyToManyField(blank=True, to='ad.Script')),
            ],
            options={
                'ordering': ('voltage', 'current'),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'FAILED'), (1, 'PASSED')], default=0, max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='logs')),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('firstEntered', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ad.card')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ad.script')),
            ],
            options={
                'ordering': ('file',),
            },
        ),
        migrations.AddField(
            model_name='card',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ad.model'),
        ),
        migrations.AddField(
            model_name='card',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ad.product'),
        ),
        migrations.AddField(
            model_name='card',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ad.station'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
