# Generated by Django 3.2.6 on 2021-12-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20211201_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ('name', 'type', 'station', 'serialNumber', 'kepcoNumber', 'calibrationDate', 'expirationDate')},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ('name', 'product', 'voltage', 'current')},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ('name', 'file', 'dvm', 'osc', 'rctrl', 'actrl', 'eload')},
        ),
        migrations.AlterField(
            model_name='log',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.card'),
        ),
        migrations.AlterField(
            model_name='log',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='actrl',
            field=models.PositiveIntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two')]),
        ),
        migrations.AlterField(
            model_name='script',
            name='dvm',
            field=models.PositiveIntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two')]),
        ),
        migrations.AlterField(
            model_name='script',
            name='eload',
            field=models.PositiveIntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two')]),
        ),
        migrations.AlterField(
            model_name='script',
            name='osc',
            field=models.PositiveIntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two')]),
        ),
        migrations.AlterField(
            model_name='script',
            name='rctrl',
            field=models.PositiveIntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two')]),
        ),
    ]
