# Generated by Django 3.2.6 on 2021-12-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_auto_20211201_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ad.script'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, choices=[('fail', 'FAILED'), ('pass', 'PASSED')], max_length=10, null=True),
        ),
    ]
